[theme]
primaryColor = "#4CAF50"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F5F5F5"
textColor = "#000000"

[server]
enableCORS = false
enableXsrfProtection = false

[client]
showSidebarNavigation = false

[ui]
hideTopBar = true
